### ISSUE TITLE
`vpcSim()` requires that etas set to zero must be in the dataset

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/nlmixr2est#341]
I set `eta.v ~ 0`, and it fit fine, but `eta.v` is required as a covariate in the dataset for `vpcSim()`:

``` r
library(nlmixr2)
#> Warning: package 'nlmixr2' was built under R version 4.2.3
#> Loading required package: nlmixr2data
#> Warning: package 'nlmixr2data' was built under R version 4.2.3

one.cmt <- function() {
  ini({
    tka <- 0.45
    tcl <- log(c(0, 2.7, 100))
    tv <- 3.45
    eta.ka ~ 0.6
    eta.cl ~ 0.3
    eta.v ~ 0
    add.sd <- 0.7
  })
  model({
    ka <- exp(tka + eta.ka)
    cl <- exp(tcl + eta.cl)
    v <- exp(tv + eta.v)
    linCmt() ~ add(add.sd)
  })
}

suppressMessages(
  fit <- nlmixr(one.cmt, theo_sd, est="focei", control = list(print = 0))
)
#> calculating covariance matrix
#> done
vpcSim(fit, pred=TRUE)
#> Model:
#> 
#> param(tka,tcl,tv,add.sd,eta.ka,eta.cl,eta.v);
#> ka~exp(tka+eta.ka);
#> cl~exp(tcl+eta.cl);
#> v~exp(tv+eta.v);
#> rx_yj_~2;
#> rx_lambda_~1;
#> rx_low_~0;
#> rx_hi_~1;
#> rx_pred_f_~linCmtA(rx__PTR__,t,0,1,1,cl,v,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,ka,0.0,1.0,0.0,0.0);
#> rx_pred_~rx_pred_f_;
#> rx_r_~(add.sd)^2;
#> ipred=rxTBSi(rx_pred_,rx_lambda_,rx_yj_,rx_low_,rx_hi_);
#> sim=rxTBSi(rx_pred_+sqrt(rx_r_)*err.rxLinCmt,rx_lambda_,rx_yj_,rx_low_,rx_hi_);
#> tad=tad();
#> cmt(rxLinCmt);
#> dvid(1);
#> Error in rxSolveSEXP(object, .ctl, .nms, .xtra, params, events, inits, : The following parameter(s) are required for solving: eta.v
```

<sup>Created on 2023-04-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by mattfidler** [comment]
This should have been fixed with the most recent version of rxode2. Can you
make sure you are using it.

**Comment by billdenney** [comment]
Let me try that.

**Comment by billdenney** [comment]
I'm running the current versions of everything, and I'm still getting the issue.
